[SONICCOLORSDEMASTERED] Improve patchscript and prepare port for new versions

diff --git a/ports/unreleased/soniccolorsdemastered/soniccolorsdemastered/tools/patchscript b/ports/unreleased/soniccolorsdemastered/soniccolorsdemastered/tools/patchscript
--- a/ports/unreleased/soniccolorsdemastered/soniccolorsdemastered/tools/patchscript
+++ b/ports/unreleased/soniccolorsdemastered/soniccolorsdemastered/tools/patchscript
@@ -1,128 +1,145 @@
 #!/bin/bash
 # Set GAMEDIR to the current directory and set logfile
 GAMEDIR="$PWD"
-LOGFILE="$GAMEDIR/patchlog.txt"
+LOGFILE="patchlog.txt"
+LOGERR="patcherr.txt"
 
 # Redirect output and error to the log file
-exec > >(tee -a "$LOGFILE") 2>&1
+> "$GAMEDIR/$LOGFILE" && exec > >(tee "$GAMEDIR/$LOGFILE") 2>&1
 echo "GAMEDIR is set to: $GAMEDIR"
 
+# Patch failure function
+patch_failure() {
+    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
+    $ESUDO umount "$TOOLKIT" 2>/dev/null || true
+    # Exit script, or return if sourced
+    return 1 2>/dev/null || exit 1
+}
+
+# Mount the GMToolkit runtime
+TOOLKIT="$HOME/gmtoolkit"
+RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
+if [ -f "$RUNTIME" ]; then
+    $ESUDO mkdir -p "$TOOLKIT"
+    $ESUDO umount "$TOOLKIT" 2>/dev/null || true
+    $ESUDO mount "$RUNTIME" "$TOOLKIT"
+else
+    echo "This port requires the GMToolkit runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
+# Mount the dotnet runtime
+DOTNETDIR="$HOME/mono"
+DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
+if [ -f "$DOTNETFILE" ]; then
+    $ESUDO mkdir -p "$DOTNETDIR"
+    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
+    $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
+else
+    echo "This port requires the Dotnet runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
 # Exports
+export PATH="$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
+export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
+export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export DATADIR="$GAMEDIR/assets"
 export DATAFILE="soniccolors.port"
-export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
-export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
-export TOOLDIR="$GAMEDIR/tools"
 export TMPDIR="$GAMEDIR/tmp"
-export PATH="$GAMEDIR/tools:$PATH"
 
 # Permissions
 chmod 666 /dev/uinput
-chmod 777 "$TOOLDIR/gmKtool.py"
-chmod 777 "$TOOLDIR/oggenc"
 
 cd "$GAMEDIR"
 
-unzip_patch() {
-    echo "Unzipping the patch file..."
-    if [ -f "./tools/patches/soniccolors.zip.001" ]; then
-        if [ -x "$(command -v 7z)" ]; then
-            ./tools/7za x ./tools/patches/soniccolors.zip.001 -o./tools/patches
-            if [ $? -eq 0 ]; then
-                echo "Patch file successfully extracted."
-                rm ./tools/patches/soniccolors.zip.*
-            else
-                echo "Failed to extract multi-part archive."
-                exit 1
-            fi
-        else
-            echo "7za tool is not available. Failed to extract xdelta patch."
-            exit 1
-        fi
+# Set up trap for cleaning TMPDIR on exit
+trap 'rm -rf "$TMPDIR"; echo "Cleaned up temporary files." >> "$LOGFILE"' 0
+
+# Attempt to get SAVEDIR from gmloader.json using jq
+if command -v jq >/dev/null 2>&1; then
+    SAVEDIR=$(jq -r '.save_dir // empty' "$GAMEDIR/gmloader.json" 2>/dev/null)
+else
+    SAVEDIR="$GAMEDIR/saves"
+fi
+
+# Test for commands: python, zip
+PYTHON=$(command -v python3)
+if [ -z "$PYTHON" ]; then
+    echo "Missing Python!"
+    patch_failure
+fi
+
+ZIP=$(command -v zip)
+if [ -z "$ZIP" ]; then
+    echo "Missing zip!"
+    patch_failure
+fi
+
+# Externalize game textures with compression
+dump_textures() {
+    # Purge cache before operations
+    rm -rf "$TMPDIR/"*
+    
+    # Begin texture operations
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        dump "$DATADIR/data.win" \
+        -e "$DATADIR/textures" "$DATADIR/game.droid"
+
+    if [ $? -ne 0 ]; then
+        echo "[DOTNET]: Texture dumping failed to apply."
+        return 1
     else
-        echo "Patch archive not found!"
-        exit 1
+        rm -f "$DATADIR/data.win"
+        mkdir -p "$SAVEDIR"
+        mv "$DATADIR/textures" "$SAVEDIR/textures"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
     fi
 }
 
-apply_xdelta() {
-    # Check if the data.win file exists and apply xdelta
-    if [ -f "$DATADIR/data.win" ]; then
-        # v0.4.1
-        output=$($controlfolder/xdelta3 -d -s "$DATADIR/data.win" -f "./tools/patches/soniccolors.xdelta" "$DATADIR/game.droid" 2>&1)
-        if [ $? -eq 0 ]; then
-            echo "Patch applied successfully"
-            echo "$output"
-            rm "$DATADIR/data.win"
-        else
-            echo "Failed to apply patch"
-            echo "$output"
-            exit 1
-        fi
-    else
-        echo "No data.win file found to patch!"
-        sleep 2
-        rm -rf patchlog.txt
-        exit 1
-    fi
-}
-
-compress_audio() {
-    mkdir -p "$TMPDIR"
-
-    # Run the compression tool
-    PYTHON=$(which python3)
-    echo "Running GMTools on data and audiogroups."
-    $PYTHON ./tools/gmKtool.py -vv -D -R 22050 -m 0 -r -b 32 -d "$TMPDIR" "$DATADIR/game.droid"
-
-    if [ $? -eq 0 ]; then
-        echo "Compression completed successfully."
-        mv "$TMPDIR/"* "$DATADIR"
-        echo "Moved compressed files to $DATADIR."
-        rmdir "$TMPDIR"
-        echo "Temporary directory $TMPDIR removed."
+compress_audio() {   
+    # Do audio compression
+    if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
+        mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
         echo "Audio compression applied successfully."
     else
-        echo "Audio compression failed."
-        echo "Cleaning up temporary directory $TMPDIR."
-        rm -rf "$TMPDIR"
+        # Failure
+        echo "Audio compression failed for $GAMEFILE."
+        rmdir "$TMPDIR"
+        return 1
     fi
 }
 
 zip_archive() {
-        zip -r -0 $DATAFILE ./assets/
-        rm -rf ./assets
-        mkdir -p saves
-}
-
-# Use move_data function while the game is fairly new and is receiving several updates.
-move_data() {
-    mkdir -p saves
-    mv -f ./assets/* ./saves
-    echo "Moved game assets to saves directory."
+        zip -r -0 "$DATAFILE" ./assets/
+        rm -rf "$DATADIR/"*
 }
 
 process_game() {
     # Delete unnecessary files
-    rm -rf $DATADIR/*.exe $DATADIR/.gitkeep
+    rm -rf $DATADIR/*.exe $DATADIR/*.dll $DATADIR/.gitkeep
     echo "Removed unnecessary files"
-
-    echo "Unpacking xdelta patch..."
-    unzip_patch
-    sleep 1
-    echo "Applying xdelta patch"
-    apply_xdelta
+    
+    echo "Externalizing textures..."
+    dump_textures || { patch_failure; return 1; }
     sleep 1
     echo "Compressing audio..."
-    compress_audio
+    compress_audio || { patch_failure; return 1; }
     sleep 1
     echo "Finishing up..."
-    zip_archive
-    sleep 1
-	
-    # Final completion message
-    echo "Patching process complete!"
+    zip_archive || { patch_failure; return 1; }
 }
 
 # Call the function
-process_game
+if ! process_game; then
+    echo "Patching process failed!"
+    mv "$LOGFILE" "$LOGERR"
+else
+    echo "Patching process complete!"
+fi
+
+# Unmount runtimes
+$ESUDO umount "$DOTNETDIR" 2>/dev/null || true
+$ESUDO umount "$TOOLKIT" 2>/dev/null || true
