[GMS TEMPLATE] Update template

diff --git a/ports/templates/gmloadernext/portfolder/tools/patchscript b/ports/templates/gmloadernext/portfolder/tools/patchscript
--- a/ports/templates/gmloadernext/portfolder/tools/patchscript
+++ b/ports/templates/gmloadernext/portfolder/tools/patchscript
@@ -2,25 +2,58 @@
 # Set GAMEDIR to the current directory and set logfile
 GAMEDIR="$PWD"
 LOGFILE="$GAMEDIR/patchlog.txt"
-LOGERR="$GAMEDIR/patch_error.txt"
 
 # Redirect output and error to the log file
-rm -f $LOGFILE $LOGERR
 exec > >(tee -a "$LOGFILE") 2>&1
 echo "GAMEDIR is set to: $GAMEDIR"
 
+# Patch failure function
+patch_failure() {
+    mv "$LOGFILE" "$LOGERR"
+    $ESUDO umount "$DOTNETDIR"
+    $ESUDO umount "$TOOLKIT"
+    echo "Patching process failed."
+    exit 1
+}
+
+# Mount the GMToolkit runtime
+TOOLKIT="$HOME/gmtoolkit"
+RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
+if [ -f "$RUNTIME" ]; then
+    $ESUDO mkdir -p "$TOOLKIT"
+    $ESUDO umount "$TOOLKIT" || true
+    $ESUDO mount "$RUNTIME" "$TOOLKIT"
+else
+    echo "This port requires the GMToolkit runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
+# Mount the dotnet runtime
+DOTNETDIR="$HOME/mono"
+DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
+if [ -f "$DOTNETFILE" ]; then
+    $ESUDO mkdir -p "$DOTNETDIR"
+    $ESUDO umount "$DOTNETFILE" || true
+    $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
+else
+    echo "This port requires the Dotnet runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
 # Exports
-export TOOLKIT="$controlfolder/utils/gmtoolkit"
-export PATH="$TOOLKIT/gmtools:$TOOLKIT/utmt-cli.${DEVICE_ARCH}:$PATH"
-export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"
+export PATH="$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
+export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
 export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export DATADIR="$GAMEDIR/assets"
-export DATAFILE="portname.port"
+export DATAFILE="utyellow.port"
 export TMPDIR="$GAMEDIR/tmp"
 
 # Permissions
 chmod 666 /dev/uinput
-chmod 755 "$TOOLKIT/gmtools/gmKtool.py" "$TOOLKIT/gmtools/oggenc.${DEVICE_ARCH}" "$TOOLKIT/gmtools/oggdec.${DEVICE_ARCH}"
+
+cd "$GAMEDIR"
 
 # Set up trap for cleaning TMPDIR on exit
 trap 'rm -rf "$TMPDIR"; echo "Cleaned up temporary files." >> "$LOGFILE"' 0
@@ -30,13 +63,6 @@ if command -v jq >/dev/null 2>&1; then
     SAVEDIR=$(jq -r '.save_dir // empty' "$GAMEDIR/gmloader.json" 2>/dev/null)
 else
     SAVEDIR="$GAMEDIR/saves"
-fi
-
-# Bail if the dotnet runtime is missing or wasn't mounted
-if ! command -v dotnet >/dev/null 2>&1; then
-    echo "Dotnet is required but not installed. Please install the runtime."
-    echo "Patching process failed."
-    exit 1
 fi
 
 # Test for commands: python, zip
@@ -52,21 +78,14 @@ if [ -z "$ZIP" ]; then
     patch_failure
 fi
 
-# PATCHING FAILED
-patch_failure() {
-    mv "$LOGFILE" "$LOGERR"
-    echo "Patching process failed."
-    exit 1
-}
-
 prepare_files() {
     mkdir -p "$SAVEDIR"
-
+    
     # Delete excess files
     find "$DATADIR" -type f \( \
         -name "*.exe" -o -name "*.dll" -o -name "*.hashdb" -o \
         -name "*.ico" -o -name "*.lnk" -o -name "*.msg" -o -name "*.zip" \
-    \) -exec rm -f {} \; 2>>"$LOGERR"
+    \) -exec rm -f {} \;
 
     # Move splash file if it exists
     if [ -f "$DATADIR/splash.png" ]; then
@@ -74,7 +93,7 @@ prepare_files() {
     fi
 }
 
-# Apply a patch to enforce stretching to fill the display
+# Apply a patch
 apply_xdelta() {
     GOG_MD5=""
     STEAM_MD5=""
@@ -83,15 +102,16 @@ apply_xdelta() {
         checksum=$(md5sum "$DATADIR/data.win" | awk '{print $1}')
         case "$checksum" in
             "$GOG_MD5")
-                PATCH="GOG.xdelta"
+                PATCH="gog.xdelta"
                 ;;
             "$STEAM_MD5")
-                PATCH="STEAM.xdelta"
+                PATCH="steam.xdelta"
                 ;;
             *)
                 echo "Unknown data.win checksum: $checksum"
                 echo "Cannot determine appropriate patch"
                 patch_failure
+                return
                 ;;
         esac
 
@@ -123,7 +143,7 @@ dump_textures() {
     rm -rf "$TMPDIR/"*
     
     # Begin texture operations
-    dotnet "$TOOLKIT/utmt-cli.${DEVICE_ARCH}/UndertaleModCli.dll" \
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
         dump "$DATADIR/data.win" \
         -e "$DATADIR/textures" "$DATADIR/game.droid"
 
@@ -137,11 +157,8 @@ dump_textures() {
     fi
 }
 
-compress_audio() {
-    # Purge cache before operations
-    rm -rf "$TMPDIR/"*
-    
-    if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -v -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
+compress_audio() {  
+    if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
         mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
         echo "Audio compression applied successfully."
     else
@@ -155,10 +172,9 @@ compress_audio() {
 zip_archive() {
         zip -r -0 "$DATAFILE" ./assets/
         echo "Zipped contents to $DATAFILE"
-        rm -rf "$GAMEDIR/assets/"*
+        rm -rf "$DATADIR"*
 }
 
-# Comment out any functions not used
 process_game() { 
     echo "Preparing game..."
     prepare_files || patch_failure 
@@ -172,9 +188,14 @@ process_game() {
     echo "Finishing up..."
     zip_archive || patch_failure
     sleep 1
+    
+    # Unmount runtimes
+    $ESUDO umount "$DOTNETDIR"
+    $ESUDO umount "$TOOLKIT"
 	
     # Final completion message
     echo "Patching process complete!"
 }
 
+# Call the function
 process_game
