[SONICTT16B] Provide additional feedback for unzip apk step

diff --git a/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript b/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript
--- a/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript
+++ b/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript
@@ -10,7 +10,6 @@ echo "GAMEDIR is set to: $GAMEDIR"
 
 # Patch failure function
 patch_failure() {
-    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
     $ESUDO umount "$TOOLKIT" 2>/dev/null || true
     # Exit script, or return if sourced
     return 1 2>/dev/null || exit 1
@@ -34,6 +33,7 @@ export PATH="$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
 export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
 export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export DATADIR="$GAMEDIR/assets"
+export TOOLDIR="$GAMEDIR/tools"
 export DATAFILE="sonictt16b.port"
 export TMPDIR="$GAMEDIR/tmp"
 
@@ -53,29 +53,40 @@ else
 fi
 
 # Test for commands: python, zip
-PYTHON=$(which python3)
+PYTHON=$(command -v python3)
 if [ -z "$PYTHON" ]; then
     echo "Missing Python!"
     patch_failure
 fi
 
-ZIP=$(which zip)
+ZIP=$(command -v zip)
 if [ -z "$ZIP" ]; then
     echo "Missing zip!"
     patch_failure
 fi
 
+UNZIP=$(command -v unzip)
+if [ -z "$UNZIP" ]; then
+    echo "Missing unzip!"
+    patch_failure
+fi
+
 unzip_apk() {
-    # Unzip the user-provided apk if it exists
     if [ -f "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk" ]; then
-    echo "Extracting apk file..."
+        echo "Extracting apk file..."
         mkdir -p "$GAMEDIR/tmp"
-        unzip "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk" -d "$GAMEDIR/tmp"
-        # Zip the lib folder into the .port file
-        (cd "$GAMEDIR/tmp" && zip -r -0 "$GAMEDIR/$DATAFILE" lib)
-        # Move the assets folder to the $GAMEDIR
-        mv "$GAMEDIR/tmp/assets" "$GAMEDIR" && rm -rf "$GAMEDIR/tmp"
-        rm -rf "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk"
+        if $UNZIP "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk" -d "$GAMEDIR/tmp"; then
+            (cd "$GAMEDIR/tmp" && $ZIP -r -0 "$GAMEDIR/$DATAFILE" lib)
+            mv "$GAMEDIR/tmp/assets" "$GAMEDIR" && rm -rf "$GAMEDIR/tmp"
+            rm -rf "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk"
+            rm -rf "$DATADIR"/*.exe "$DATADIR"/*.png "$DATADIR"/.txt "$DATADIR"/.gitkeep
+        else
+            echo "Error unzipping apk!"
+            return 1
+        fi
+    else
+        echo "Did not find $GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk!"
+        return 1
     fi
 }
 
@@ -90,8 +101,7 @@ apply_xdelta() {
         else
             echo "Failed to apply patch"
             echo "$output"
-            mv $LOGFILE $LOGERR
-            exit 1
+            return 1
         fi
     else
         echo "No data.win file found to patch!"
@@ -106,21 +116,20 @@ compress_audio() {
         # Failure
         echo "Audio compression failed for $GAMEFILE."
         rmdir "$TMPDIR"
-        patch_failure
+        return 1
     fi
 }
 
 zip_archive() {
-        zip -r -0 $DATAFILE ./assets/
+        $ZIP -r -0 $DATAFILE ./assets/
         mkdir -p saves
         rm -rf assets
 }
 
 process_game() {
-    unzip_apk
-    # Delete unnecessary files
-    rm -rf $DATADIR/*.exe $DATADIR/*.png $DATADIR/.txt $DATADIR/.gitkeep
-    echo "Removed unnecessary files"
+
+    echo "Looking for apk file..."
+    unzip_apk || { patch_failure; return 1; }
     echo "Applying xdelta patch"
     apply_xdelta || { patch_failure; return 1; }
     echo "Compressing audio..."
@@ -138,5 +147,4 @@ else
 fi
 
 # Unmount runtimes
-$ESUDO umount "$DOTNETDIR" 2>/dev/null || true
 $ESUDO umount "$TOOLKIT" 2>/dev/null || true
