[RELEASES] Add new and update
- Update IOSAS to toggle stretch to fit
- Add new port app Oracles Randomizer NG
- Update SOH2 to v2.0.1

diff --git a/ports/released/gamemakerengine/islesofseaandsky/iosas/tools/patchscript b/ports/released/gamemakerengine/islesofseaandsky/iosas/tools/patchscript
--- a/ports/released/gamemakerengine/islesofseaandsky/iosas/tools/patchscript
+++ b/ports/released/gamemakerengine/islesofseaandsky/iosas/tools/patchscript
@@ -198,6 +198,26 @@ replace_code() {
     fi
 }
 
+# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
+set_flags() {
+    export SET_FLAGS="Fullscreen"
+    export CLEAR_FLAGS="Scale"
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        load "$DATADIR/data.win" \
+        -s "$GAMEDIR/tools/toggleflags.csx" \
+        -o "$DATADIR/data2.win"
+        
+    if [ $? -ne 0 ]; then
+        echo "Failed to toggle info flags."
+        return 1
+    else
+        echo "Successfully toggled info flags."
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+    fi
+}
+
 # Externalize game textures with compression
 dump_textures() {
     # Purge cache before operations
@@ -253,6 +273,8 @@ process_game() {
     modify_code || { patch_failure; return 1; }
     echo "Repacking gml scripts..."
     replace_code || { patch_failure; return 1; }
+    echo "Toggling GeneralInfo flags..."
+    set_flags || { patch_failure; return 1; }
     echo "Externalizing textures..."
     dump_textures || { patch_failure; return 1; }
     sleep 1
