[YEOTRILOGY] Adjust screen_init code (again) and add toggle flags csx script

diff --git a/ports/released/gamemakerengine/yeotrilogy/arrestofastonebuddha/arrestofastonebuddha/tools/patchscript b/ports/released/gamemakerengine/yeotrilogy/arrestofastonebuddha/arrestofastonebuddha/tools/patchscript
--- a/ports/released/gamemakerengine/yeotrilogy/arrestofastonebuddha/arrestofastonebuddha/tools/patchscript
+++ b/ports/released/gamemakerengine/yeotrilogy/arrestofastonebuddha/arrestofastonebuddha/tools/patchscript
@@ -146,7 +146,6 @@ dump_code() {
     # Specify which code entries to extract
     CODE_ENTRIES=(
         "gml_Script_screen_init"
-        "gml_Object_obj_options_21_Create_0"
     )
 
     CODEARGS=""
@@ -206,7 +205,27 @@ replace_code() {
     fi
 }
 
-compress_audio() {
+# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
+set_flags() {
+    export SET_FLAGS="Fullscreen"
+    export CLEAR_FLAGS="Scale"
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        load "$DATADIR/data.win" \
+        -s "$GAMEDIR/tools/toggleflags.csx" \
+        -o "$DATADIR/data2.win"
+        
+    if [ $? -ne 0 ]; then
+        echo "Failed to toggle info flags."
+        return 1
+    else
+        echo "Successfully toggled info flags."
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+    fi
+}
+
+compress_audio() {   
     # Test for data.win
     if [ -f "$DATADIR/data.win" ]; then
         mv "$DATADIR/data.win" "$DATADIR/game.droid"
@@ -235,6 +254,9 @@ process_game() {
     unzip_game
     echo "Preparing game..."
     prepare_files || { patch_failure; return 1; }
+    echo "Setting info flags..."
+    set_flags || { patch_failure; return 1; }
+    echo "Dumping game code..."
     dump_code || { patch_failure; return 1; }
     echo "Modifying gml scripts..."
     modify_code || { patch_failure; return 1; }
diff --git a/ports/released/gamemakerengine/yeotrilogy/friendsofringo/friendsofringo/tools/patchscript b/ports/released/gamemakerengine/yeotrilogy/friendsofringo/friendsofringo/tools/patchscript
--- a/ports/released/gamemakerengine/yeotrilogy/friendsofringo/friendsofringo/tools/patchscript
+++ b/ports/released/gamemakerengine/yeotrilogy/friendsofringo/friendsofringo/tools/patchscript
@@ -101,7 +101,6 @@ dump_code() {
     # Specify which code entries to extract
     CODE_ENTRIES=(
         "gml_GlobalScript_screen_init"
-        "gml_Object_obj_options_129_Create_0"
     )
 
     CODEARGS=""
@@ -161,7 +160,47 @@ replace_code() {
     fi
 }
 
-compress_audio() {
+# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
+set_flags() {
+    export SET_FLAGS="Fullscreen"
+    export CLEAR_FLAGS="Scale"
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        load "$DATADIR/data.win" \
+        -s "$GAMEDIR/tools/toggleflags.csx" \
+        -o "$DATADIR/data2.win"
+        
+    if [ $? -ne 0 ]; then
+        echo "Failed to toggle info flags."
+        return 1
+    else
+        echo "Successfully toggled info flags."
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+    fi
+}
+
+# Externalize game textures with compression
+dump_textures() {
+    # Purge cache before operations
+    rm -rf "$TMPDIR/"*
+    
+    # Begin texture operations
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        dump "$DATADIR/data.win" \
+        -e "$DATADIR/textures" "$DATADIR/game.droid"
+
+    if [ $? -ne 0 ]; then
+        echo "[DOTNET]: Texture dumping failed to apply."
+        return 1
+    else
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/textures" "$SAVEDIR/textures"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+    fi
+}
+
+compress_audio() {   
     # Test for data.win
     if [ -f "$DATADIR/data.win" ]; then
         mv "$DATADIR/data.win" "$DATADIR/game.droid"
@@ -188,11 +227,16 @@ zip_archive() {
 process_game() {
     echo "Preparing game..."
     prepare_files || { patch_failure; return 1; }
+    echo "Setting info flags..."
+    set_flags || { patch_failure; return 1; }
+    echo "Dumping game code..."
     dump_code || { patch_failure; return 1; }
     echo "Modifying gml scripts..."
     modify_code || { patch_failure; return 1; }
     echo "Repacking gml scripts..."
     replace_code || { patch_failure; return 1; }
+    echo "Externalizing textures..."
+    dump_textures || { patch_failure; return 1; }
     echo "Compressing audio..."
     compress_audio || { patch_failure; return 1; }
     echo "Finishing up..."
