[PIZZA TOWER] Use gmtoolkit runtime

diff --git a/ports/released/gamemakerengine/pizzatower/pizzatower/tools/patchscript b/ports/released/gamemakerengine/pizzatower/pizzatower/tools/patchscript
--- a/ports/released/gamemakerengine/pizzatower/pizzatower/tools/patchscript
+++ b/ports/released/gamemakerengine/pizzatower/pizzatower/tools/patchscript
@@ -2,24 +2,56 @@
 # Set GAMEDIR to the current directory and set logfile
 GAMEDIR="$PWD"
 LOGFILE="$GAMEDIR/patchlog.txt"
-START_TIME=$(date +%s)
+LOGERR="$GAMEDIR/patchlog_error.txt"
 
 # Redirect output and error to the log file
-rm -rf $LOGFILE $LOGERR
 exec > >(tee -a "$LOGFILE") 2>&1
 echo "GAMEDIR is set to: $GAMEDIR"
 
+# Patch failure function
+patch_failure() {
+    mv "$LOGFILE" "$LOGERR"
+    echo "Patching process failed."
+    exit 1
+}
+
+# Mount the GMToolkit runtime
+TOOLKIT="$HOME/gmtoolkit"
+RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
+if [ -f "$RUNTIME" ]; then
+    $ESUDO mkdir -p "$TOOLKIT"
+    $ESUDO umount "$RUNTIME" || true
+    $ESUDO mount "$RUNTIME" "$TOOLKIT"
+else
+    echo "This port requires the GMToolkit runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
+# Mount the dotnet runtime
+DOTNETDIR="$HOME/mono"
+DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
+if [ -f "$DOTNETFILE" ]; then
+    $ESUDO mkdir -p "$DOTNETDIR"
+    $ESUDO umount "$DOTNETFILE" || true
+    $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
+else
+    echo "This port requires the Dotnet runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
 # Exports
-export TOOLKIT="$controlfolder/utils/gmtoolkit"
-export PATH="$TOOLKIT/gmtools:$TOOLKIT/utmt-cli.${DEVICE_ARCH}:$PATH"
-export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"
+export PATH="$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
+export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
 export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export DATADIR="$GAMEDIR/assets"
 export LICENSEDIR="$GAMEDIR/licenses/pizzatower"
-export DATAFILE="$GAMEDIR/pizzatower.port"
+export DATAFILE="pizzatower.port"
 export TMPDIR="$GAMEDIR/tmp"
 
-cd "$GAMEDIR"
+# Permissions
+chmod 666 /dev/uinput
 
 # Set up trap for cleaning TMPDIR on exit
 trap 'rm -rf "$TMPDIR"; echo "Cleaned up temporary files." >> "$LOGFILE"' 0
@@ -31,11 +63,17 @@ else
     SAVEDIR="$GAMEDIR/saves"
 fi
 
-# Bail if the dotnet runtime is missing or wasn't mounted
-if ! command -v dotnet >/dev/null 2>&1; then
-    echo "Dotnet is required but not installed. Please install the runtime."
-    echo "Patching process failed."
-    exit 1
+# Test for commands: python, zip
+PYTHON=$(which python3)
+if [ -z "$PYTHON" ]; then
+    echo "Missing Python!"
+    patch_failure
+fi
+
+ZIP=$(which zip)
+if [ -z "$ZIP" ]; then
+    echo "Missing zip!"
+    patch_failure
 fi
 
 prepare_assets() {
@@ -49,7 +87,7 @@ prepare_assets() {
     mv "$DATADIR/sound" "$SAVEDIR/sound"
     
     # Move game licenses to our license folder
-    mkdir -p $LICENSEDIR
+    mkdir -p "$LICENSEDIR"
     [ -d "$DATADIR/licenses" ] && mv "$DATADIR/licenses/"* "$LICENSEDIR"
     rmdir "$DATADIR/licenses"
 }
@@ -62,13 +100,12 @@ purge_datafile() {
     # Attempt to unzip
     if ! unzip -q "$DATAFILE" "lib/*" -d "$TMPDIR"; then
         echo "[PURGE_DATAFILE]: Failed to unzip $DATAFILE"
-        exit 1
+        patch_failure
     fi
 
     # Remove unwanted architecture
     if [ -d "$TMPDIR/lib/armeabi-v7a" ]; then
         rm -rf "$TMPDIR/lib/armeabi-v7a"
-        echo "Removed armeabi-v7a libraries"
     fi
 
     # Repackage the cleaned content
@@ -77,7 +114,7 @@ purge_datafile() {
 
     if ! zip -r -0 -q "$GAMEDIR/$(basename "$DATAFILE")" .; then
         echo "[PURGE_DATAFILE]: Failed to create new datafile."
-        exit 1
+        patch_failure
     fi
 
     cd "$GAMEDIR"
@@ -90,7 +127,7 @@ dump_textures() {
     rm -rf "$TMPDIR/"*
     
     # Begin texture operations
-    dotnet "$TOOLKIT/utmt-cli.${DEVICE_ARCH}/UndertaleModCli.dll" \
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
         dump "$DATADIR/data.win" \
         -e "$DATADIR/textures" "$DATADIR/game.droid"
 
@@ -122,10 +159,9 @@ process_game() {
     zip_archive || { echo "Patching process failed."; exit 1; }
     sleep 1
     
-    # Measure time to complete
-	END_TIME=$(date +%s)
-    DURATION=$((END_TIME - START_TIME))
-    echo "Script completed in $DURATION seconds"
+    # Unmount runtimes
+    $ESUDO umount "$DOTNETDIR"
+    $ESUDO umount "$TOOLKIT"
     
     # Final completion message
     echo "Patching process complete!"
