[DELTARUNE] Use gmtoolkit runtime for patching

diff --git a/ports/released/gamemakerengine/deltarune/deltarune/tools/patchscript b/ports/released/gamemakerengine/deltarune/deltarune/tools/patchscript
--- a/ports/released/gamemakerengine/deltarune/deltarune/tools/patchscript
+++ b/ports/released/gamemakerengine/deltarune/deltarune/tools/patchscript
@@ -11,10 +11,29 @@ rm -f "$LOGERR"
 exec > >(tee -a "$LOGFILE") 2>&1
 echo "GAMEDIR is set to: $GAMEDIR"
 
+# Patch failure function
+patch_failure() {
+    mv "$LOGFILE" "$LOGERR"
+    echo "Patching process failed."
+    exit 1
+}
+
+# Mount the GMToolkit runtime
+TOOLKIT="$HOME/gmtoolkit"
+RUNTIME="$controlfolder/libs/gmtoolkit.${DEVICE_ARCH}.squashfs"
+if [ -f "$RUNTIME" ]; then
+    $ESUDO mkdir -p "$TOOLKIT"
+    $ESUDO umount "$RUNTIME" || true
+    $ESUDO mount "$RUNTIME" "$TOOLKIT"
+else
+    echo "This port requires the GMToolkit runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
 # Exports
-export TOOLKIT="$controlfolder/utils/gmtoolkit"
-export PATH="$TOOLKIT/gmtools:$TOOLKIT/utmt-cli.${DEVICE_ARCH}:$PATH"
-export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"
+export PATH="$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
+export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
 export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export INSTALLDIR="$GAMEDIR/assets/install"
 export ASSETDIR="$GAMEDIR/assets"
@@ -22,7 +41,6 @@ export TMPDIR="$GAMEDIR/tmp"
 
 # Permissions
 chmod 666 /dev/uinput
-chmod 755 "$TOOLKIT/gmtools/gmKtool.py" "$TOOLKIT/gmtools/oggenc.${DEVICE_ARCH}" "$TOOLKIT/gmtools/oggdec.${DEVICE_ARCH}"
 
 # Set up trap for cleaning TMPDIR on exit
 trap 'rm -rf "$TMPDIR"; echo "Cleaned up temporary files." >> "$LOGFILE"' 0
@@ -52,13 +70,6 @@ if [ -z "$ZIP" ]; then
     echo "Missing zip!"
     patch_failure
 fi
-
-# PATCHING FAILED
-patch_failure() {
-    mv "$LOGFILE" "$LOGERR"
-    echo "Patching process failed."
-    exit 1
-}
 
 # SANITIZE THE INSTALL DIRECTORIES
 sanitize() {
@@ -152,7 +163,7 @@ dump_textures() {
     rm -rf "$TMPDIR/"*
     
     # Begin texture operations
-    dotnet "$TOOLKIT/utmt-cli.${DEVICE_ARCH}/UndertaleModCli.dll" \
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
         dump "$INSTALLDIR/assets/data.win" \
         -e "$INSTALLDIR/assets/textures" "$INSTALLDIR/assets/game.droid"
 
@@ -282,6 +293,9 @@ process_game() {
             fi
         done
     fi
+    
+    $ESUDO umount "$RUNTIMEDIR"
+    echo "Patching process complete!"
 }
 
 process_game
