[GMS] Purge older dumped textures during update patches

diff --git a/ports/released/gamemakerengine/victoryheatrally/vhr/tools/patchscript b/ports/released/gamemakerengine/victoryheatrally/vhr/tools/patchscript
--- a/ports/released/gamemakerengine/victoryheatrally/vhr/tools/patchscript
+++ b/ports/released/gamemakerengine/victoryheatrally/vhr/tools/patchscript
@@ -169,21 +169,23 @@ replace_code() {
 # Externalize game textures with compression
 dump_textures() {
     # Purge cache before operations
-    rm -rf "$TMPDIR/"*
-    
-    # Begin texture operations
-    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
-        dump "$DATADIR/data.win" \
-        -e "$DATADIR/textures" "$DATADIR/game.droid"
+    [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
 
-    if [ $? -ne 0 ]; then
+    # Begin texture operations
+    if ! dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        dump "$DATADIR/data.win" \
+        -e "$DATADIR/textures" "$DATADIR/game.droid"; then
         echo "[DOTNET]: Texture dumping failed to apply."
         return 1
-    else
-        rm -f "$DATADIR/data.win"
-        mv "$DATADIR/textures" "$SAVEDIR/textures"
-        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
     fi
+
+    # Cleanup & move textures
+    rm -f "$DATADIR/data.win"
+    [ -d "$SAVEDIR/textures" ] && rm -rf "$SAVEDIR/textures"
+    mv "$DATADIR/textures" "$SAVEDIR/textures"
+
+    # Final cleanup
+    [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
 }
 
 compress_audio() {
